name: cron

on:
  schedule:
    - cron: '1 * * * *'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Execute
      run: |
        go mod download
        go run zenn_dev.go -s zenn -f ./zenn.json
        go run qiita.go

    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        add: '["zenn.json", "qiita.json"]'
        default_author: github_actions
